// vite-next-mf/remote-solid/src/index.tsx
import { render } from 'solid-js/web'
import './index.css'
import App, { AppProps } from './App'


declare global {
  interface Window {
    __SOLID_APP__: (container: HTMLElement, props: AppProps) => () => void
  }
}

window.__SOLID_APP__ = (container, props) => {
  return render(() => <App {...props} />, container)
}

// vite-next-mf/remote-vite-ts/src/index.tsx
import App, { AppProps } from './App.tsx'
import { createRoot } from "react-dom/client"

declare global {
  interface Window {
    __MF_APP__: (container: HTMLElement, props?: AppProps) => () => void
  }
}

window.__MF_APP__ = (container, props) => {
  const root = createRoot(container)
  root.render(<App {...props} />)
  return () => root.unmount();
}
