// vite-next-mf/remote-vite-ts/src/App.tsx
import { useState } from 'react'
import './App.css'

export type AppProps = {
  message?: string
}

function App(props: AppProps) {
  const [count, setCount] = useState(0)
  return (
    <div><p>From parent "{props.message}"</p>
      <div className="group">
        <button onClick={() => setCount(p => p - 1)}>-</button>
        <div className="button">
          {count}
        </div>
        <button onClick={() => setCount(p => p + 1)}>+</button>
      </div>
    </div>
  )
}

export default App

// vite-next-mf/remote-solid/src/App.tsx
import { createSignal } from 'solid-js'
import './App.css'

export type AppProps = {
  message: string
}

function App(props: AppProps) {
  console.log("SOLID CONSOLE", props)
  const [count, setCount] = createSignal(0)

  return (
    <main data-name='solid-app'>
      <button onClick={() => setCount((count) => count + 1)}>
        count is {count()} - Solid
      </button>
    </main>
  )
}

export default App
